-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgU1DgBY2P/lWEWejD
GtbxiQuPzqSf23ZhU2ftOhMSaJOgCgYIKoZIzj0DAQehRANCAAQCnxL0Nbkq2V+E
9xEP7Ua66Pj21IWyvjW1OMaHqNczfzTJqUBptyLIjQbek2TfKno0HQm/55tYP7iy
H3wgFuIw
-----END PRIVATE KEY-----