name: campus_pro
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://devel84oper.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.1+2


environment:
  sdk: '>=3.3.4 <4.0.0'
  # sdk: ">=2.12.0 <3.0.0"
  # sdk: ">=2.7.0 <3.0.0"

dependencies:
  # html_editor_enhanced:
  flutter:
    sdk: flutter
  logger: ^1.0.0
  connectivity: ^3.0.3
  http: ^1.2.1
  flutter_bloc: ^7.3.3
  bloc: ^7.2.1
  equatable: ^2.0.4
  image_picker: ^0.8.6+1
  image_crop: ^0.4.0
#  flutter_absolute_path: ^1.0.6
  provider: ^6.0.3
  shared_preferences: ^2.0.5
  shimmer: ^2.0.0
  bot_toast: ^4.0.1
  # google_fonts: ^2.0.0
  google_fonts: ^6.2.1
  intl: ^0.19.0
  firebase_core: ^2.1.1
  firebase_auth: ^4.1.1
  firebase_messaging: ^14.2.1
  flutter_local_notifications: ^17.2.1+2
  cloud_firestore: ^4.3.1
  googleapis: ^13.1.0
  googleapis_auth: ^1.1.0
  google_sign_in: ^5.0.7
  multi_select_flutter: ^4.0.0
  horizontal_data_table: ^4.1.4
  flutter_image_compress: ^1.0.0
  table_calendar: ^3.1.1
  percent_indicator: ^4.2.2
#  charts_flutter: ^0.12.0
  fl_chart: ^0.55.2
  file_picker: ^5.2.10
  lazy_load_scrollview: ^1.3.0
  url_launcher: ^6.0.9
  #  File Downloaders
  dio: ^4.0.0
  path_provider: ^2.0.2
#  downloads_path_provider_28: ^0.1.0
  permission_handler: ^10.2.0
  open_file: ^3.0.1
  # flutter_downloader: ^1.6.1

       #  Web View
  # flutter_webview_plugin:
  #   git: https://github.com/nuc134r/flutter_webview_plugin.git
  # flutter_webview_plugin: ^0.4.0
  webview_flutter: ^3.0.4
  flutter_inappwebview: ^5.8.0
  flutter_spinkit: ^5.1.0
  xml2json: ^5.3.1
  crypto: ^3.0.0
  device_info_plus: ^4.0.0
  # flutter_native_timezone: ^1.0.10
  rxdart: ^0.26.0
  # Fetch Location & Address
  geolocator: ^9.0.2
#  geocoder: ^0.2.1
  # Google map dependency`

  google_maps_flutter: ^2.6.1
  # location: ^4.2.2
  flutter_tts: ^3.2.2
  flutter_holo_date_picker: ^1.0.1+2
#  flutter_google_places: ^0.3.0
  uuid: ^3.0.5
  animations: ^2.0.2

#  permission: ^0.1.7

  flutter_polyline_points: ^2.0.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  alert_dialog: ^1.0.0
  syncfusion_flutter_xlsio: ^25.1.38
  excel: ^2.0.1
  universal_html: ^2.0.8
  # flutter_quill:
  flutter_html:
  #  delta_markdown:
  #  markdown: 
  animated_text_kit: ^4.2.1
#  device_preview: ^1.1.0
  firebase_analytics:
  sqflite: ^2.0.2
  flutter_svg: ^1.0.3
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
#  flutter_downloader:


# dependency_overrides:
#   flutter_colorpicker: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  build_runner: ^2.4.9
  freezed: ^2.5.2
  json_serializable: ^6.8.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/fonts/
    - assets/drawer/
    # - assets/packages/html_editor_enhanced/summernote.html
    # - assets/packages/html_editor_enhanced/summernote-no-plugins.html
    # - assets/packages/html_editor_enhanced/summernote-lite.min.css
    # - assets/packages/html_editor_enhanced/summernote-lite-dark.css
    # - assets/packages/html_editor_enhanced/summernote-lite.min.js
    # - packages/html_editor_enhanced/jquery.min.js
    # - packages/html_editor_enhanced/font/summernote.eot
    # - packages/html_editor_enhanced/font/summernote.ttf
    # - packages/html_editor_enhanced/plugins/summernote-at-mention/summernote-at-mention.js

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:

  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSansVariableFontRegular.ttf
    - family: SourceSansPro
      fonts:
        - asset: assets/fonts/SourceSansPro/SourceSansPro-Bold.ttf
        - asset: assets/fonts/SourceSansPro/SourceSansPro-SemiBold.ttf
        - asset: assets/fonts/SourceSansPro/SourceSansPro.ttf
    - family: BebasNeue
      fonts:
        - asset: assets/fonts/BebasNeue-Regular.ttf
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
