# # Uncomment the next line to define a global platform for your project
platform :ios, '14.0'
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

 project 'Runner', {
   'Debug' => :debug,
   'Profile' => :release,
   'Release' => :release,
 }

 def flutter_root
   generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
   unless File.exist?(generated_xcode_build_settings_path)
     raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
   end

   File.foreach(generated_xcode_build_settings_path) do |line|
     matches = line.match(/FLUTTER_ROOT\=(.*)/)
     return matches[1].strip if matches
   end
   raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
 end

 require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

 flutter_ios_podfile_setup

 target 'Runner' do
   use_frameworks!
   use_modular_headers!


    #  pod 'FirebaseFirestore', :git => 'https://github.com/invertase/firestore-ios-sdk-frameworks.git', :tag => '7.11.0'

     pod 'Firebase/Auth'
     pod 'FBSDKLoginKit'
     pod 'Firebase/Messaging'
     pod 'Firebase'
   flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
 end

 post_install do |installer|
   installer.pods_project.targets.each do |target|
     flutter_additional_ios_build_settings(target)
 
        target.build_configurations.each do |config|
        # config.build_settings['ENABLE_BITCODE'] = 'YES'
        # config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
        # end
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= [
          '$(inherited)',
          # 'PERMISSION_MICROPHONE=1',
        ]
      end
       target_is_resource_bundle = target.respond_to?(:product_type) && target.product_type == 'com.apple.product-type.bundle'
       target.build_configurations.each do |build_configuration|
         if target_is_resource_bundle
           build_configuration.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
           build_configuration.build_settings['CODE_SIGNING_REQUIRED'] = 'NO'    
           build_configuration.build_settings['CODE_SIGNING_IDENTITY'] = '-'
           build_configuration.build_settings['EXPANDED_CODE_SIGN_IDENTITY'] = '-'
         end
        end
   end
 end
# target 'ImageNotification' do
#   use_frameworks!
#   pod 'Firebase/Messaging'
# end



